### ISSUE TITLE
Error: Invalid Folder Path 

### ISSUE THREAD

**Issue by LazyCat420** [diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI#17]
set up the venv and was able to install requirements but get a Error : Invalid folder path when i run python run_app_gui.py. Is there folders I have to create/files I need to move into the env in order for it to work? 

`Error: Invalid folder path.
Traceback (most recent call last):
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/run_app_gui.py", line 309, in <module>
    main()
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/run_app_gui.py", line 93, in main
    window = sg.Window(APP_TITLE,layout,finalize=True, resizable=True,enable_close_attempted_event=False,background_color=color.GRAY_9900)
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 9614, in __init__
    self.Finalize()
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 10300, in finalize
    self.Read(timeout=1)
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 10075, in read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 10146, in _read
    self._Show()
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 9886, in _Show
    StartupTK(self)
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 16866, in StartupTK
    _convert_window_to_tk(window)
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 16753, in _convert_window_to_tk
    PackFormIntoFrame(window, master, window)
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 15991, in PackFormIntoFrame
    PackFormIntoFrame(element, labeled_frame, toplevel_form)
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 15991, in PackFormIntoFrame
    PackFormIntoFrame(element, labeled_frame, toplevel_form)
  File "/home/fuckyou/workspace/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/venv/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 15520, in PackFormIntoFrame
    max_line_len = max([len(str(l)) for l in element.Values]) if len(element.Values) else 0
TypeError: object of type 'NoneType' has no len()`

**Comment by Kobaayyy** [comment]
the same problem, can u tell me how to solve it, thx~

**Comment by aerique** [comment]
For others coming here and being frustrated at the lack of an answer: the tool wants to start in `~/Documents`, at least for Linux and OSX. So either  create that directory or change the code in https://github.com/diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI/blob/main/util/file_explorer_component.py#L82-L87
