### ISSUE TITLE
Error when running run_app_gui.exe

### ISSUE THREAD

**Issue by MitchOkabe** [diStyApps/Safe-and-Stable-Ckpt2Safetensors-Conversion-Tool-GUI#18]
After extracting the zip file, I tried running the run_app_gui.exe file and received this error:

![image](https://user-images.githubusercontent.com/13142459/215282581-c4232442-791a-4f74-aa1a-63d3daf028b9.png)

Traceback (most recent call last):
  File "run_app_gui.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "torch\__init__.py", line 192, in <module>
    from torch._C import *  # noqa: F403
ImportError: DLL load failed: The specified module could not be found.

**Comment by diStyApps** [comment]
Hi, what system are you on? Do you have Python installed?
